image: python:3.8-slim

before_script:
- pip install -r requirements.txt

stages:
- generate 

generate_scripts:
  stage: generate
  script:
  - python aliasci.py -o ./out/
  artifacts:
    paths:
      - ./out/
