[all]
# Aliases used for all command lines
gs = "git status"
ga = "git add"
gaa = "git add --all"
gaap = "git add --all -p"
gch = "git checkout"
gchb = "git checkout -b"
gc = "git commit"
gcm = "git commit -m"
gps = "git push"
gpl = "git pull"
gplr = "git pull --rebase"

[bash]
# Aliases used only for the Bourne-again shell (BASH)
x = "clear && ls"
dev = "pushd ~/dev && clear && ls"
".." = "cd .. && clear && ls"
"..." = "cd ../.. && clear && ls"
"...." = "cd ../../.. && clear && ls"
"....." = "cd ../../../.. && clear && ls"

[ps]
# Aliases only used for windows PowerShell

[cmd]
# Aliases only used for windows cmd
ls = "dir"

[fish]
# Aliases only used for the Linux friendly interactive shell (FISH)
x = "clear & ls"
dev = "pushd ~/dev & clear & ls"
".." = "cd .. & clear & ls"
"..." = "cd ../.. & clear & ls"
"...." = "cd ../../.. & clear & ls"
"....." = "cd ../../../.. & clear & ls"

[cmder]
# Aliases only used for the console emulator cmder (https://cmder.net)
